# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-19 16:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('quantity', models.FloatField()),
                ('measuresize', models.CharField(choices=[('PNCH', 'PINCH'), ('TSP', 'TSP'), ('TBSP', 'TBSP'), ('CUP', 'CUP'), ('PINT', 'PINT'), ('QT', 'QUART'), ('GAL', 'GALLON'), ('G', 'GRAM'), ('KG', 'KILOGRAM'), ('OZ', 'OUNCE'), ('FLOZ', 'FLUID OUNCE')], default='TBSP', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('recipename', models.CharField(max_length=50)),
                ('yields', models.IntegerField()),
                ('portionsize', models.CharField(max_length=50)),
                ('dateadded', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Recipes'),
        ),
    ]
