# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='static/about-black-1240x600.jpg', upload_to='recipes'),
        ),
        migrations.AddField(
            model_name='steps',
            name='step_image',
            field=models.ImageField(default='static/about-black-1240x600.jpg', upload_to='steps'),
        ),
    ]
