# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170726_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='yieldsize',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='', upload_to='recipes'),
        ),
        migrations.AlterField(
            model_name='steps',
            name='step_image',
            field=models.ImageField(default='static/about-black-1240x600.jpg', upload_to=''),
        ),
    ]
