# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170726_1825'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipename',
            new_name='recipenme',
        ),
    ]
