# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170726_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipes',
            old_name='recipenme',
            new_name='recipename',
        ),
        migrations.RemoveField(
            model_name='recipes',
            name='yieldsize',
        ),
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.ImageField(default='static/about-black-1240x600.jpg', upload_to='recipes'),
        ),
    ]
