# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170726_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='stepno',
            field=models.CharField(max_length=2),
        ),
    ]
