# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-26 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20170726_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='stepno',
            field=models.IntegerField(),
        ),
    ]
