# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170726_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steps',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
