# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170726_2050'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='steps',
            unique_together=set([('recipe', 'stepno')]),
        ),
    ]
