# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 22:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20170726_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='ingredient',
            field=models.CharField(default='flour', max_length=50),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.FloatField(default='100'),
        ),
        migrations.AlterField(
            model_name='ingredients',
            name='recipe',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='api.Recipes'),
        ),
    ]
