# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-28 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170727_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='portionsize',
            field=models.CharField(default='Enter Portion Size', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipename',
            field=models.CharField(default='Enter A Recipe Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='username',
            field=models.ForeignKey(default='https://quiet-citadel-22666.herokuapp.com/user/1/', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='yields',
            field=models.IntegerField(default='0'),
        ),
    ]
