# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-03 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20170727_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
